name: Claude Assistant

on:
  issue_comment:               { types: [created] }
  pull_request_review_comment: { types: [created] }
  pull_request_review:         { types: [submitted] }

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment'            && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review'      && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest

    permissions:               # ← OIDC 取得に必須
      id-token: write
      contents: read
      pull-requests: read
      issues: read

    steps:
      - uses: actions/checkout@v4

      - name: Claude Code Action (Max OAuth)
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at:    ${{ secrets.CLAUDE_EXPIRES_AT }}