name: Deploy Widget to CDN

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type to bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Wrangler
        run: npm install -g wrangler
      
      - name: Build widget
        run: npm run widget:build
      
      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Deploy to Cloudflare R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # 環境変数が正しく設定されていることを確認（値は表示せず）
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "Error: CLOUDFLARE_API_TOKEN is not set"
            exit 1
          fi
          
          if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
            echo "Error: CLOUDFLARE_ACCOUNT_ID is not set"
            exit 1
          fi
          
          echo "Deploying widget version v${{ steps.package-version.outputs.version }} to Cloudflare R2..."
          
          # バージョン付きディレクトリにデプロイ
          npx wrangler r2 object put \
            --bucket=timebid-cdn \
            --binding=WIDGET_BUCKET \
            "widget/${{ steps.package-version.outputs.version }}/" \
            --path="./dist/widget/" \
            --recursive
          
          # latestディレクトリにデプロイ
          npx wrangler r2 object put \
            --bucket=timebid-cdn \
            --binding=WIDGET_BUCKET \
            "widget/latest/" \
            --path="./dist/widget/" \
            --recursive
            
          echo "✅ Widget successfully deployed to Cloudflare R2"
      
      - name: Create deployment summary
        run: |
          echo "## Widget Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Successfully deployed widget version **${{ steps.package-version.outputs.version }}** to CDN" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### CDN URLs" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Latest version: \`https://cdn.timebid.com/widget/latest/timebid-widget.iife.js\`" >> $GITHUB_STEP_SUMMARY
          echo "- Specific version: \`https://cdn.timebid.com/widget/${{ steps.package-version.outputs.version }}/timebid-widget.iife.js\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Embed Code Example" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```html' >> $GITHUB_STEP_SUMMARY
          echo '<script src="https://cdn.timebid.com/widget/${{ steps.package-version.outputs.version }}/timebid-widget.iife.js"></script>' >> $GITHUB_STEP_SUMMARY
          echo '<div id="timebid-container"></div>' >> $GITHUB_STEP_SUMMARY
          echo '<script>' >> $GITHUB_STEP_SUMMARY
          echo '  document.addEventListener("DOMContentLoaded", function() {' >> $GITHUB_STEP_SUMMARY
          echo '    const widget = TimeBid.createWidget({' >> $GITHUB_STEP_SUMMARY
          echo '      apiKey: "YOUR_API_KEY",' >> $GITHUB_STEP_SUMMARY
          echo '      containerId: "timebid-container",' >> $GITHUB_STEP_SUMMARY
          echo '      theme: { primaryColor: "#3498db" }' >> $GITHUB_STEP_SUMMARY
          echo '    });' >> $GITHUB_STEP_SUMMARY
          echo '  });' >> $GITHUB_STEP_SUMMARY
          echo '</script>' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
