name: Refresh Claude Tokens (Magic-Link)

on:
  schedule:
    - cron: '50 17 * * *'        # UTC 17:50 = JST 02:50 (毎日)
  workflow_dispatch:             # 手動実行も可

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write            # gh secret set に必要

    steps:
      - name: Install Claude CLI latest
        run: npm i -g @anthropic-ai/claude-code@latest

      - name: Ensure jq is present
        run: sudo apt-get update && sudo apt-get -y install jq

      - name: Refresh using existing refreshToken
        env:
          ACCESS:  ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          REFRESH: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          EXPIRES: ${{ secrets.CLAUDE_EXPIRES_AT }}
        run: |
          mkdir -p ~/.claude
          cat > ~/.claude/.credentials.json <<EOF
          {
            "claudeAiOauth": {
              "accessToken":  "$ACCESS",
              "refreshToken": "$REFRESH",
              "expiresAt":    $EXPIRES
            }
          }
          EOF

          # CLI が refresh → 新 credential を JSON 出力
          claude /export-credentials > new.json
          NEW_ACCESS=$(jq -r '.accessToken'  new.json)
          NEW_REFRESH=$(jq -r '.refreshToken' new.json)
          NEW_EXPIRES=$(jq -r '.expiresAt'    new.json)

          gh secret set CLAUDE_ACCESS_TOKEN  -b"$NEW_ACCESS"
          gh secret set CLAUDE_REFRESH_TOKEN -b"$NEW_REFRESH"
          gh secret set CLAUDE_EXPIRES_AT    -b"$NEW_EXPIRES"